### ISSUE TITLE
API issues after installing SSL

### ISSUE THREAD

**Issue by minershaven** [minernl/Miningcore.WebUI#10]
everything seemed to be working until i used certbot to install ssl on my page.  now the api doesnt work anymore and just returns a ERR_SSL_PROTOCOL_ERROR message.  are there any changes that need to be made after you get ssl installed ?   issue seems to be that its a page being served over HTTPS calling for functions that are being served over HTTP.

**Comment by ghost** [comment]
did you fixed it ?
