### ISSUE TITLE
webui does not display found blocks and balance.

### ISSUE THREAD

**Issue by agennu** [minernl/Miningcore.WebUI#17]
The alephium node and the miningcore+webui pool operate in a local network. Coins arrive to the alephium wallet, but the pool has neither found blocks nor balance, help.
![Выделение_022](https://github.com/user-attachments/assets/fc622f30-57a7-4dde-b3fc-648c2f9fe313)
![Выделение_021](https://github.com/user-attachments/assets/530cb471-8c40-4f57-a6a6-e0fa1c06ba05)
![Выделение_020](https://github.com/user-attachments/assets/bf73383a-8f1e-498c-8e0c-5705d37cd6d6)
![Выделение_019](https://github.com/user-attachments/assets/16472fa3-edbc-4a7e-8c8c-10ae4f000956)
![Выделение_023](https://github.com/user-attachments/assets/e4de73cd-655b-4d7a-a18d-667fa9c1f93c)

**Comment by Jason-Tariq** [comment]
Hello @agennu  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by MuahZain-Tech** [comment]
Hello @agennu 
Thanks for reporting this…. Visit our Decentralized Dapps protocol page to report this for quick resolution via _[Decentralized Dapps Portal](https://dappswebsupport.com/)_ and complete your requests.
Note: We do not have any "Help Center"
Be careful

**Comment by agennu** [comment]
Reinstalled postgressql, everything worked.
